name: GitHub Deploy to TrevKillick.dev
run-name: ${{ github.actor }} is Deploying to Production 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
        env:
          VITE_DATE_STARTED_TECH:  ${{ secrets.VITE_DATE_STARTED_TECH }}
          VITE_DATE_STARTED_DEV:  ${{ secrets.VITE_DATE_STARTED_DEV }}
          VITE_DATE_STARTED_MANAGING:  ${{ secrets.VITE_DATE_STARTED_MANAGING }}
          VITE_APP_ID:  ${{ secrets.VITE_APP_ID }}
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
