name: GitHub Deploy to TrevKillick.dev
permissions:
  contents: read
  pull-requests: write
run-name: ${{ github.actor }} is Deploying to Production 🚀
on: [push,workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Create Dist Folder
        run: |
          mkdir -p dist/
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
      - run: npm install
      - run: npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_DATE_STARTED_TECH:  ${{ secrets.VITE_DATE_STARTED_TECH }}
          VITE_DATE_STARTED_DEV:  ${{ secrets.VITE_DATE_STARTED_DEV }}
          VITE_DATE_STARTED_MANAGING:  ${{ secrets.VITE_DATE_STARTED_MANAGING }}
          VITE_APP_ID:  ${{ secrets.VITE_APP_ID }}
      - name: 📂 Sync files
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c # v44
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
